name: cypp450
dependencies:
  - numpy
  - pandas
  - python=3.9
  - plotly
  - typing
  - molvs
  - rdkit
  - PyTDC
  - scikit-optimize
  - pandas-profiling[notebook]
  - feature_engine
  - mlxtend
  - xgboost
  - catboost
  - Jinja2
  - lightgbm
  - shap