name: cypp4502
dependencies:
  - numpy
  - pandas
  - python=3.10
  - plotly
  - typing
  - molvs
  - rdkit
  - PyTDC
  - scikit-optimize
  - pandas-profiling[notebook]
  - feature_engine
  - mlxtend
  - xgboost